### ISSUE TITLE
_utf8_urlencode brokes list url-parameters

### ISSUE THREAD

**Issue by VVasyaev** [MarketSquare/robotframework-requests#234] opened 2019-07-22 15:23 UTC
As part of current job i need to check array-type url-parameters.
Like:
    `http://www.google.com/?ids[]=1&ids[]=2&ids[]=3`

To get parameters with same names its possible to pass its values as list.
Like:
```
${values}    Create List    1    2    3
${params}    Create Dictionary    ids[]=${values}
```

Unfortunately robotframework-requests library's making any list-parameter to be string at the **_utf8_urlencode** method -- so my dictionary gets **ids[]="[1,2,3]"** instead of what it was before. So its impossible to pass array-parameters.

I've just remove **_utf8_urlencode** call and its working well.

Could you please look into that?

**Comment by lucagiove** [comment] 2019-09-24 06:57
but removing that function still urlencode the values?

**Comment by lucagiove** [comment] 2019-09-24 07:02
looking at the requests code the encoding should be already performed so it might work, could you submit a test that shows this bug and a PR with the fix?

**Comment by lucagiove** [comment] 2020-03-20 23:47
Would be really useful a test to demonstrate this bug, I think it will be fixed with the new keywords that wont add any additional data parsing.

**Comment by lucagiove** [comment] 2020-05-20 22:51
I cannot reproduce the problem, during the 0.8 development I made the following tests and always worked (also tested with  `Get Request` keyword)

```
Get Request With Url Duplicated Keys In Params
    [Tags]  get
    ${array}=          Create List   1  2
    ${resp}=            GET On Session  ${GLOBAL_SESSION}  /anything
    ...                     params=key=1&key=2
    Status Should Be    OK  ${resp}
    Lists Should Be Equal  ${array}  ${resp.json()}[args][key]

Get Request With Url Duplicated Keys In Params And PHP Style Array
    [Tags]  get
    ${array}=          Create List   1  2
    ${resp}=            GET On Session  ${GLOBAL_SESSION}  /anything
    ...                     params=key[]=1&key[]=2
    Status Should Be    OK  ${resp}
    Lists Should Be Equal  ${array}  ${resp.json()}[args][key[]]

Get Request With Url Params As PHP Style Array
    [Tags]  get
    ${resp}=            GET On Session  ${GLOBAL_SESSION}  /anything
    ...                     params=key[]=1,2
    Status Should Be    OK  ${resp}
    Should Be Equal As Strings  1,2  ${resp.json()}[args][key[]]

Get Request With Url Params As Array
    [Tags]  get
    ${resp}=            GET On Session  ${GLOBAL_SESSION}  /anything
    ...                     params=key=[1,2]
    Status Should Be    OK  ${resp}
    Should Be Equal As Strings  [1,2]  ${resp.json()}[args][key]Get Request With Url Duplicated Keys In Params
    [Tags]  get
    ${array}=          Create List   1  2
    ${resp}=            GET On Session  ${GLOBAL_SESSION}  /anything
    ...                     params=key=1&key=2
    Status Should Be    OK  ${resp}
    Lists Should Be Equal  ${array}  ${resp.json()}[args][key]

Get Request With Url Duplicated Keys In Params And PHP Style Array
    [Tags]  get
    ${array}=          Create List   1  2
    ${resp}=            GET On Session  ${GLOBAL_SESSION}  /anything
    ...                     params=key[]=1&key[]=2
    Status Should Be    OK  ${resp}
    Lists Should Be Equal  ${array}  ${resp.json()}[args][key[]]

Get Request With Url Params As PHP Style Array
    [Tags]  get
    ${resp}=            GET On Session  ${GLOBAL_SESSION}  /anything
    ...                     params=key[]=1,2
    Status Should Be    OK  ${resp}
    Should Be Equal As Strings  1,2  ${resp.json()}[args][key[]]

Get Request With Url Params As Array
    [Tags]  get
    ${resp}=            GET On Session  ${GLOBAL_SESSION}  /anything
    ...                     params=key=[1,2]
    Status Should Be    OK  ${resp}
    Should Be Equal As Strings  [1,2]  ${resp.json()}[args][key]
```

**Closed by lucagiove** 2020-05-20 22:51 UTC
